debug: ${DEBUG:false}
trace: false

server:
  port: 9100

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  #    database-platform: org.hibernate.dialect.MySQL5Dialect}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agdxapi}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  data:
    web:
      pageable:
        one-indexed-parameters: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

springdoc:
  show-actuator: true
  default-produces-media-type: "application/json"
  #  pathsToMatch: /api/v1/**, /actuator/**
  pathsToMatch: /api/v1/**
  api-docs:
    path: /agdx-api
    groups:
      enabled: false
  swagger-ui:
    tags-sorter: alpha
#    operations-sorter: alpha

cip:
  name: 'AgDx API'
  version: '1.0.0-beta1'
  desc: 'Description here'
  externaldoc: '1.0.0-beta1'
  license: '1.0.0-beta1'