debug: ${DEBUG:false}
trace: false

server:
  port: 9100


spring:
  jpa:
    hibernate:
      ddl-auto: none
  #    database-platform: org.hibernate.dialect.MySQL5Dialect}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agdxapi}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
