debug: ${DEBUG:false}
trace: false

server:
  port: 9100


spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  #    database-platform: org.hibernate.dialect.MySQL5Dialect}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agdxapi}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  data:
    web:
      pageable:
        one-indexed-parameters: true

springdoc:
  show-actuator: true
  pathsToMatch: /api/v1/**
  api-docs:
    path: /agdx-api
  swagger-ui:
    #    tags-sorter: alpha
    operations-sorter: alpha

cip:
  name: 'AgDx API'
  version: '1.0.1'
  desc: 'Description here'
  externaldoc: '1.0.1'
  license: '1.0.1'