debug: ${DEBUG:false}
trace: ${TRACE:false}

server:
  port: 9100


spring:
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.MySQL5Dialect}
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agdxapi}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

springdoc:
  show-actuator: false
  default-produces-media-type: "application/json"
  #  pathsToMatch: /api/v1/**, /actuator/**
  pathsToMatch: /api/v1/**
  api-docs:
    path: /agdx-api
    groups:
      enabled: true
  swagger-ui:
    #    tags-sorter: alpha
    operations-sorter: method

agdx:
  name: 'AgDx API'
  version: ${VERSION:1.0.2}
  desc: 'Description here'
  externaldoc: ${agdx.version}
  license: ${agdx.version}
  contact:
    name: ${agdx.name}
    email: agdx@agdx.org
    url: agdx.org
