spring:
  liquibase:
    change-log: "classpath:db/changelog.xml"
    enabled: true

  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.MySQL5Dialect}
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  ## default connection pool
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agdxapi}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
