spring:
  liquibase:
    change-log: "classpath:db/changelog.xml"
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  ## default connection pool
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/api}
    username: ${DATABASE_USERNAME:api-user}
    password: ${DATABASE_PASSWORD:api-pass}
